import Head from "next/head";
import NLink from "next/link";
import { BrowserRouter, Link as RRLink, Route, Switch } from "react-router-dom";
import { Footer } from "../components/Footer/Footer";
import styles from "../styles/Home.module.css";

export default function App() {
  return (
    <div className={styles.container}>
      <Head>
        <title>pages/[...everythingElse]</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {typeof window !== "undefined" && (
          <BrowserRouter>
            <Switch>
              <Route exact path="/app">
                <h1 className={styles.title}>App Home</h1>

                <div className={styles.grid}>
                  <RRLink to="/fake-route">
                    <a>Go to 404</a>
                  </RRLink>

                  <NLink href="/">
                    <a>Go to landing</a>
                  </NLink>
                </div>
              </Route>

              <Route>
                <h1 className={styles.title}>404 - Page Not Found</h1>

                <div className={styles.grid}>
                  <RRLink to="/app">
                    <a>Go to app</a>
                  </RRLink>

                  <NLink href="/">
                    <a>Go to landing</a>
                  </NLink>
                </div>
              </Route>
            </Switch>
          </BrowserRouter>
        )}
      </main>

      <Footer />
    </div>
  );
}
