import Head from 'next/head';
import Image from 'next/image';
import NLink from 'next/link';
import { Footer } from '../components/Footer/Footer';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>pages/index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <NLink href="/fakeee">
            <a>/fakeee</a>
          </NLink>
          <NLink href="/app">
            <a>/app</a>
          </NLink>
        </div>
      </main>

      <Footer />
    </div>
  );
}
